### ISSUE TITLE
First attempt with acarsserv

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/acarsserv#1]
Before using JSON I first wanted to see if it works using the basic acarsserv interface.
So I started vdlm2dec like this:
/home/pi/vdlm2dec/vdlm2dec -n 10.0.0.34:5555 -l "/home/pi/vdlm2dec/logs/vdl2_rtlsdr-11_$(date +"%Y%m%d").log" -p -1 -r 00000011 136.725 136.775 136.825 136.875 136.975 >> "/home/pi/vdlm2dec/logs/process-vdlm2dec.log" 2>&1 &  
which works fine as the logfile proves.

Started acarsserv like this:
/home/pi/acarsserv/acarsserv -a -v -n 10.0.0.34:5555 >> "/home/pi/acarsserv/logs/process-acarsserv.log" 2>&1 &

But no matter how long I wait, the program never seems to use any cpu.
  ps -e | grep acars
  1021 pts/0    00:00:00 acarsserv
And there are no messages in the process-acarsserv.log

What am I doing wrong?
Is only JSON suported?
 -n addr:port		send to addr:port UDP packets in **json** that could be read by acarsserv 

Cheers,
Dick

**Comment by TLeconte** [comment]
vdlm2dec send only json packets. I had to tell it  more clearly  in the README ....

**Comment by DickvanNoort** [comment]
If vdlm2dec only sends JSON packets, then maybe the -j  argument is not needed.
From vdlm2dec -help:
 -j :                   json output
 -n addr:port :                 send to addr:port UDP pakets in json
