### ISSUE TITLE
Use same arguments in all programs (cosmetic)

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/acarsserv#3]
To set the acarsserv port  vdlm2dec uses a lowercase "n" and acarsserv uses an uppercase "N".
In vdlm2dec the
 -n addr:port		send to addr:port UDP packets in json that could be read by acarsserv

in acarsserv the
-N address:port : listen on given address:port (default : *:5555)

**Comment by TLeconte** [comment]
Yes it lacks coherency.
I will not change acarsdec parameters because its the older and most used programs.
I will change networks parameters for vdlm2dec and acarsserv ...

**Comment by DickvanNoort** [comment]
Thank you.
