### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by trcyprkr** [TLeconte/acarsserv#4]
pi@raspberrypi:~/acarsserv $ make -f Makefile
cc -Wall -Ofast -pthread  -I.     -c -o acarsserv.o acarsserv.c
cc -Wall -Ofast -pthread  -I.     -c -o dbmgn.o dbmgn.c
dbmgn.c:5:21: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
                     ^
compilation terminated.
<builtin>: recipe for target 'dbmgn.o' failed
make: *** [dbmgn.o] Error 1
pi@raspberrypi:~/acarsserv $

**Comment by trcyprkr** [comment]
ok fixed the compile error.  Forgot to install libsqlite3-dev

**Comment by dterweij** [comment]
Another one:
-Ofast does not work on CentOS 6, just remove it and it compile fine.

**Comment by TLeconte** [comment]
It must be because CentOS 6 use an old gcc version 
On  a gcc 7.3 it works.
