### ISSUE TITLE
Any reason JSON messages missing flight are dropped?

### ISSUE THREAD

**Issue by gtjoseph** [TLeconte/acarsserv#8]
Even though there's an empty flight field in the message, I'd still want the message written to Messages.  Even still written to Flights if the tail number is present.

**Comment by az1zul** [comment]
Hi, any one has solution on this?

**Comment by az1zul** [comment]
> Even though there's an empty flight field in the message, I'd still want the message written to Messages. Even still written to Flights if the tail number is present.

found a temporary solution for this, set tail number as flight number if flight number didn't exists.
